include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Project-specific rule customizations
    public_member_api_docs: false
    avoid_print: false
    lines_longer_than_80_chars: false

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    deprecated_member_use_from_same_package: ignore
