// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXW_gQuL25GRLjxTjFaB-rKLiZB5RTVk',
    appId: '1:1058303346843:web:c5420d5a78f696eb6bde3e',
    messagingSenderId: '1058303346843',
    projectId: 'attendrix-app',
    authDomain: 'attendrix-app.firebaseapp.com',
    storageBucket: 'attendrix-app.firebasestorage.app',
    measurementId: 'G-PDRWN6M40H',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7kVGAE8wWISKt8I9SCBhtn2BSmfVB1sU',
    appId: '1:1058303346843:android:9ef3c48e93fab0016bde3e',
    messagingSenderId: '1058303346843',
    projectId: 'attendrix-app',
    storageBucket: 'attendrix-app.firebasestorage.app',
  );
}
